# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runSimulation <- function(N, v, c, mu, max_time, pHawk_init, output_nth_generation) {
    invisible(.Call('_driftSim_runSimulation', PACKAGE = 'driftSim', N, v, c, mu, max_time, pHawk_init, output_nth_generation))
}

